#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "borgserver"
name = "Borg Server"
description.en = "Offer backup storage to a friend"
description.fr = "Offrez un espace de stockage à un⋅e ami⋅e"

version = "1.4.1~ynh1"

maintainers = ["ljf"]

[upstream]
license = "BSD-3-Clause"
website = "https://www.borgbackup.org/"
admindoc = "https://borgbackup.readthedocs.io/en/stable/"
code = "https://github.com/borgbackup/borg"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.ssh_user]
    ask.en = "Indicate the SSH user to create"
    ask.fr = "Indiquez l'utilisateur SSH à créer"
    type = "string"
    example = "john"

    [install.public_key]
    ask.en = "Indicate the public key given by borg_ynh app"
    ask.fr = "Indiquez la clé publique donnée par l'app borg_ynh"
    type = "string"

    [install.alert_delay]
    ask.en = "After which delay in days should we alert if there are no changes on repo ?"
    ask.fr = "Après quel délais en jours devons-nous lancer une alerte si il n'y a pas de changement dans le repo ?"
    type = "string"
    default = "1"

    [install.alert_mails]
    ask.en = "Emails to whom send alerts ?"
    ask.fr = "Emails des personnes à qui envoyer les alertes ?"
    type = "string"
    default = "root"
    example = "camille@example.com,eden@example.com"

    [install.quota]
    ask.en = "Indicate the storage quota"
    ask.fr = "Indiquez le quota de stockage"
    type = "string"
    optional = true
    example = "30G"

[resources]
    [resources.sources.main]
    url = "https://github.com/borgbackup/borg/archive/refs/tags/1.4.1.tar.gz"
    sha256 = "b8c6ac0b03cf7f2673004754515f5abca6379ffd947a4be77dc210e7d4c5da59"
    # Only here to bump the package version
    prefetch = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/borgbackup/borg"

    [resources.system_user]
    # Not really useful, but required for install_dir

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = [
        "python3",
        "python3-dev",
        "python3-pip",
        "python3-venv",
        "libacl1-dev",
        "libssl-dev",
        "liblz4-dev",
        "libzstd-dev",
        "libxxhash-dev",
        "libfuse3-dev",
        "pkg-config",
    ]
