#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.ssh_user = "sam"
    args.public_key = "ssh-ed25519 AAAACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    args.alert_delay = 1
    args.alert_mails = "sam@domain.tld"
    args.quota = "1G"
