#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_print_info "Borg backup repo in $data_dir won't be backup to avoid backup of backup loop issue."

ynh_backup "$data_dir/.ssh"
ynh_backup "/etc/ssh/ssh_config.d/$app.conf"
ynh_backup "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
