#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
export app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
ynh_export ssh_user public_key

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_save_args ssh_user public_key

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_install_app_dependencies $pkg_dependencies
pip3 install setuptools --upgrade
pip3 install borgbackup

#=================================================
# CREATE SSH USER USED BY BORG
#=================================================
adduser $ssh_user --quiet --gecos ",,," --shell /bin/bash --disabled-password

#=================================================
# AUTORIZE SSH FOR THIS USER
#=================================================
home=/home/$ssh_user
mkdir -p /home/$ssh_user/.ssh
touch /home/$ssh_user/.ssh/authorized_keys
echo "command=\"borg serve --restrict-to-path /home/$ssh_user/backup\",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc $public_key" >> /home/$ssh_user/.ssh/authorized_keys

#=================================================
# AVOID BACKUP OF BACKUP
#=================================================
touch $home/.nobackup
mkdir -p /etc/yunohost/hooks.d/backup
cp -f ../conf/17-data_home /etc/yunohost/hooks.d/backup/17-data_home

