#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Creating system user..."

#=================================================
# CONFIGURE DATA DIRECTORY
#=================================================
ynh_script_progression "Configuring data directory..."

# Tweak to prevent the backup of the backup itself
touch "$data_dir/.nobackup"
touch "$data_dir/.ssh/authorized_keys"
chown -R "$app:$app" "$data_dir"
chmod -R u=rwX,go=--- "$data_dir"

#=================================================
# INSTALL BORG
#=================================================
ynh_script_progression "Installing Borg..."

install_borg_with_pip

#=================================================
# CONFIGURE SSH
# See https://borgbackup.readthedocs.io/en/stable/usage/serve.html#ssh-configuration
# We choose dash because it is small, fast and has reduced number of built-ins
#=================================================
ynh_script_progression "Configuring ssh..."

ynh_config_add --template="sshd_config.conf" --destination="/etc/ssh/ssh_config.d/$app.conf"

chsh -s /bin/dash "$app"

#=================================================
# SET UP CRON
#=================================================
ynh_script_progression "Configuring cron to monitor backup..."

ynh_config_add --template="monitor-backup.cron" --destination="/etc/cron.d/$app"
ynh_config_add --template="helpers.sh" --destination="$install_dir/helpers.sh"
ynh_config_add --template="monitor-backup.sh" --destination="$install_dir/monitor-backup.sh"
chmod +x "$install_dir/helpers.sh"
chmod +x "$install_dir/monitor-backup.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
