#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DELETE USER BUT KEEP FILES
#=================================================
# We keep files cause we don't know what the user want to do about
# backups stored in the home directory

ynh_script_progression "Deleting system user..."

#=================================================
# REMOVE SSH CONFIG
#=================================================

ynh_script_progression "Removing ssh configuration..."
ynh_safe_rm "$data_dir/.ssh"
ynh_safe_rm "/etc/ssh/ssh_config.d/$app.conf"

#=================================================
# REMOVE CRON FILES
#=================================================

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
