#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..."

# Remove borg if we are removing the last borg app on the system
if [ "$(yunohost app list | grep "id: borg" | wc -l)" == "1" ] ; then 
    ynh_secure_remove "/opt/borg-env"
    ynh_secure_remove "/usr/local/bin/borg"
fi

#=================================================
# REMOVE USER BUT KEEP FILES
#=================================================
# We keep files cause we don't know what the user want to do about
# backups stored in the home directory

ynh_system_user_delete --username=$ssh_user

#=================================================
# REMOVE CRON FILES
#=================================================

ynh_secure_remove "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
