#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Remove legacy stuff
if [ -f "/etc/apt/sources.list.d/$app-stretch-backports.list" ]; then
    ynh_safe_rm "/etc/apt/sources.list.d/$app-stretch-backports.list"
fi

if [ -f "/etc/yunohost/hooks.d/backup/17-data_home" ]; then
    ynh_safe_rm "/etc/yunohost/hooks.d/backup/17-data_home"
fi

# Clear legacy stuff
if [ -d /opt/borg-env ]; then
    ynh_safe_rm "/opt/borg-env"
    ynh_safe_rm "/usr/local/bin/borg"
    ynh_safe_rm "/usr/local/bin/backup-with-borg"
fi

# Fix broken value ssh_user that mistakenly got replaced by the public key in previous versions...
[ -n "${ssh_user:-}" ] || ynh_die "Unable to retrieve ssh_user please fix /etc/yunohost/apps/$app/settings.yml manually :( !"
if echo "$ssh_user" | grep -q ' '; then
    ssh_user=$(grep "$ssh_user" /home/*/.ssh/authorized_keys | grep borg | cut -d/ -f3)
    [ -n "$ssh_user" ] || ynh_die "Unable to retrieve ssh_user please fix /etc/yunohost/apps/$app/settings.yml manually :( !"
    ynh_app_setting_set --key=ssh_user --value="$ssh_user"
fi

if echo "$public_key" | grep -q -v ' '; then
    ynh_app_setting_set --key=public_key --value="$(grep -Po 'no-user-rc \K.*$' "/home/$ssh_user/.ssh/authorized_keys")"
fi

# Alert delay and alert mail missing
if [ -z "${alert_delay:-}" ]; then
    ynh_app_setting_set --key=alert_delay --value="1"
    ynh_app_setting_set --key=alert_mails --value="root"
fi

#=================================================
# UPGRADE BORG
#=================================================
ynh_script_progression "Upgrading Borg..."

install_borg_with_pip

#=================================================
# AUTORIZE SSH FOR THIS USER
#=================================================
ynh_script_progression "Making sure SSH user exists with appropriate permissions..."

ynh_system_user_create --username="$ssh_user" --home_dir="/home/$ssh_user" --use_shell --groups ssh.app
mkdir -p "/home/$ssh_user"
chmod 700 "/home/$ssh_user"
chown "$ssh_user" "/home/$ssh_user"

# Tweak to prevent the backup of the backup itself
touch "/home/$ssh_user/.nobackup"

create_ssh_config "/home/$ssh_user/.ssh" "/home/$ssh_user/backup"

#=================================================
# SETUP CRON
#=================================================
ynh_script_progression "Configuring cron to monitor backup..."

ynh_config_add --template="monitor-backup.cron" --destination="/etc/cron.d/$app"
ynh_config_add --template="monitor-backup.sh" --destination="$install_dir/monitor-backup.sh"
chmod +x "$install_dir/monitor-backup.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
