#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Remove legacy stuff
if [ -f "/etc/apt/sources.list.d/$app-stretch-backports.list" ]; then
    ynh_safe_rm "/etc/apt/sources.list.d/$app-stretch-backports.list"
fi

if [ -f "/etc/yunohost/hooks.d/backup/17-data_home" ]; then
    ynh_safe_rm "/etc/yunohost/hooks.d/backup/17-data_home"
fi

# Clear legacy stuff
if [ -d /opt/borg-env ]; then
    ynh_safe_rm --file="/opt/borg-env"
    ynh_safe_rm --file="/usr/local/bin/borg"
    ynh_safe_rm --file="/usr/local/bin/backup-with-borg"
fi

if ynh_app_upgrading_from_version_before_or_equal_to "1.4.0~ynh1"; then
    ynh_script_progression "Retrieving old configuration..."
    # Get previous settings values
    [ -n "${ssh_user:-}" ] || ynh_die "Unable to retrieve ssh_user please fix /etc/yunohost/apps/$app/settings.yml manually :( !"
    if echo "$ssh_user" | grep -q ' '; then
        ssh_user=$(grep "$ssh_user" /home/*/.ssh/authorized_keys | grep borg | cut -d/ -f3)
        [ -n "$ssh_user" ] || ynh_die "Unable to retrieve ssh_user please fix /etc/yunohost/apps/$app/settings.yml manually :( !"
    fi
    if echo "$public_key" | grep -q -v ' '; then
        default_public_key="$(grep -Po 'no-user-rc \K.*$' "/home/$ssh_user/.ssh/authorized_keys")"
    fi
    if [ -z "$quota" ]; then
        quota=""
    fi
    if [ -z "$alert_delay" ]; then
        alert_delay=""
    fi
    if [ -z "$alert_mails" ]; then
        alert_mails="root"
    fi

    ynh_script_progression "Creating new configuration..."
    # Create new configuration
    cp -a "/home/$ssh_user/*" "$data_dir/" # Necessary as data directory wasn't configured with data_dir variable
    chown -R "$app:$app" "$data_dir"
    chmod -R u=rwX,go=--- "$data_dir"
    # See https://borgbackup.readthedocs.io/en/stable/usage/serve.html#ssh-configuration
    chsh -s /bin/dash "$app"
    repository_to_add="$ssh_user"
    create_repository
    configure_repository "$repository_to_add" "$default_public_key" "$quota"
    ynh_app_setting_set --key="${repository_to_add}_public_key" --value="$default_public_key"
    ynh_app_setting_set --key="${repository_to_add}_quota" --value="$quota"
    ynh_app_setting_set --key="${repository_to_add}_alert_delay" --value="$alert_delay"
    ynh_app_setting_set --key="${repository_to_add}_alert_mails" --value="$alert_mails"

    ynh_script_progression "Removing old configuration..."
    # Remove old configuration
    ynh_system_user_delete --username="$ssh_user" # Necessary as user was manually created
    ynh_safe_rm "/home/$ssh_user"
    ynh_app_setting_delete --key="ssh_user"
    ynh_app_setting_delete --key="public_key"
    ynh_app_setting_delete --key="alert_delay"
    ynh_app_setting_delete --key="alert_mails"
fi

#=================================================
# UPGRADE BORG
#=================================================
ynh_script_progression "Upgrading Borg..."

install_borg_with_pip

ynh_config_add --template="monitor-backup.cron" --destination="/etc/cron.d/$app"
ynh_config_add --template="helpers.sh" --destination="$install_dir/helpers.sh"
ynh_config_add --template="monitor-backup.sh" --destination="$install_dir/monitor-backup.sh"
# See https://borgbackup.readthedocs.io/en/stable/usage/serve.html#ssh-configuration
ynh_config_add --template="sshd_config" --destination="/etc/ssh/ssh_config.d/$app.conf"
chmod +x "$install_dir/helpers.sh"
chmod +x "$install_dir/monitor-backup.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
